# Generated by Django 4.0.1 on 2022-01-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='current_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='gain_loss',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='purchase_price',
            field=models.IntegerField(null=True),
        ),
    ]
