# Generated by Django 4.0.1 on 2022-01-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_company_current_price_company_gain_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='face_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='lot_size',
            field=models.IntegerField(null=True),
        ),
    ]
