from django.urls import path,include
from .views import *

urlpatterns = [
    path('', index, name= 'index'),
    path('counselor/', counselor, name= 'counselor'),
    path('services/', services, name= 'services'),
    path('pricing/', pricing, name= 'pricing'),
    path('login/', login, name= 'login'),
    path('logout/', logout, name='logout'),
    path('profile/', profileDetails, name= 'profile'),
    path('postprofiledetails/', postprofiledetails, name= 'postprofiledetails'),
    path('home/', home, name = 'home'),
    path('sellrequest/', sellrequest, name = 'sellrequest'),
    path('sell_list/', sellList, name = 'sell_list'),
    path('sellDelete/<int:id>', sellDelete, name='sellDelete'),
    path('postsell/', postsell, name = 'postsell'),
    path('change_password/', password, name = 'change_password'),
    path('register/', register, name = 'register'),
    path('startup/', startup, name = 'startup'),
    path('ipos/', ipos, name = 'ipos'),
    path('unlisted/', unlisted, name = 'unlisted'),
    path('trade/', trade, name = 'trade'),
    path('sell/', sell, name = 'sell'),
    path('ipo/', ipo, name = 'ipo'),
    path('share/', share, name = 'share'),
    path('bankers/', bankers, name = 'bankers'),
    path('equity/', equity, name = 'equity'),
    path('blog/', blog, name = 'blog'),
    path('blog-post/', blog_post, name = 'blog-post'),
    path('contact/', contact, name = 'contact'),
    path('term/', term, name = 'term'),
    path('risk/', risk, name = 'risk'),
    path('rating/', rating, name = 'rating'),
    path('privacy/', privacy, name = 'privacy'),
    path('about/', about, name = 'about'),
    path('company/', company, name = 'company'),
    path('disclaimer/', disclaimer, name = 'disclaimer'),
    path('company_details/<int:id>', company_details, name = 'company_details'),
    path('purchase/<int:id>', purchase, name='purchase'),
    path('notification/', notification, name='notification'),
    path('message/', message, name='message'),
    path('post_message/', postMessage, name='post_message'),
    path('company_des/<name>/', companyDes, name='company_des')
]
